# Generated by Django 4.0.4 on 2022-04-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_mark_type_posts_carmodel_auto_car_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='posted_date',
        ),
    ]
